http {
    limit_req_zone $binary_remote_addr zone=per_client:10m rate=10r/m;

    upstream backend_servers {
        server echo:80;
    }

    server {
        listen 80;

        location / {
            limit_req zone=per_client burst=2 nodelay;
            limit_req_status 429;
            proxy_pass http://backend_servers;
        }
    }
}

events {}
